
[general]
	disable_mod = false
	auto_start = false
	space_modules = false
	shadow_text = true
	animations = false
	animationSpeed = 1.0
	fontScale = 1.0
	background_color = 0
	hide_debug_crosshair = true
	hide_sidebar = true
	hide_bossbar = true
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = false
		chunk_relative_coords = false
		chunk_coords = false

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	memory_color_toggle = true
	time_format = "HH:mm:ss"
	enabled = true

	[modules_right.lines]
		time = false
		java_version = false
		memory_usage = true
		allocation_rate = false
		allocated_memory = false
		cpu = false
		display = false
		gpu = false
		gpu_utilization = false
		opengl_version = false
		gpu_driver = false

